apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: spring-cont
        image: 837553127105.dkr.ecr.us-east-1.amazonaws.com/spring:5-1b4f2c0
        ports:
        - containerPort: 8081
